# Generated by Django 3.2.12 on 2022-12-20 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_question_has_choices'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='has_choices',
        ),
    ]
